### ISSUE TITLE
Ukloniti Moodle Moot banner

### ISSUE THREAD

**Issue by schlos** [HrOpen-Croatia/open.hr#8]
<img class="size-full wp-image-1744 alignnone" src="http://www.open.hr/wp-content/uploads/2015/09/moodle-moot-2015-logoy.png" alt="moodle-moot-2015-logoy" width="450" height="182">

Klikom na banner, link je mrtav (http://webmoodlemoot.org/)

Moodle Moot je prosao 24.10.2015. pa bi umjesto ovog bannera trebalo staviti neki noviji sadrzaj.

**Comment by sveby** [comment]
Tnx na prijavi, riješeno!
